#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom --experimental-backends &
nitrogen --restore &
polybar main &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        4
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal border color "#0"
bspc config active_border_color "#8F8AAC"
bspc config focused_border_color "#8F8AAC"
bspc presel_feedback_color "#8F8AAC"
bspc config urgent_border_color "#8F8AAC"